import { EntityStateMeta } from "../../../Common/Crafting/interfaces";
import { getRndInteger } from "../../../Common/Utilities";

export const generateRareItemName = (stateMeta: EntityStateMeta) => {
  const prefixRoll = getRndInteger(0, rareNamePrefixes.length - 1);
  const prefix = rareNamePrefixes[prefixRoll];

  const itemClass = stateMeta.state.baseItem.item_class;
  const possibleSuffixes = getPossibleSuffixes(stateMeta);

  let suffix = "";
  if (possibleSuffixes.length > 0) {
    const sufixRoll = getRndInteger(0, possibleSuffixes.length - 1);
    suffix = possibleSuffixes[sufixRoll];
  } else {
    console.log("Failed to find a suffix for the item class: " + itemClass);
  }

  const rareItemName = `${prefix} ${suffix}`;
  return rareItemName;
};

const getPossibleSuffixes = (stateMeta: EntityStateMeta): string[] => {
  let suffixLookupColumn: string | undefined;
  const itemClass = stateMeta.state.baseItem.item_class;
  const itemName = stateMeta.state.baseItem.name;

  if (itemClass === "Shield" && itemName.includes("Spirit Shield")) {
    suffixLookupColumn = "spirit shields";
  } else {
    // Use the item class for looking up what names are possible
    suffixLookupColumn = itemClassSuffixLookup[itemClass];
  }

  if (suffixLookupColumn && rareNameSuffixes[suffixLookupColumn]) {
    return rareNameSuffixes[suffixLookupColumn];
  }
  return [];
};

/**  A mapping between item classes and which suffix columns to look for suffixes in */
const itemClassSuffixLookup = {
  Claw: "claws",
  Dagger: "daggers",
  Wand: "wands",
  Shield: "shields",
  "One Hand Sword": "swords",
  "Thrusting One Hand Sword": "swords",
  "One Hand Mace": "maces",
  "One Hand Axe": "axes",
  Sceptre: "sceptres",
  Bow: "bows",
  Staff: "staves",
  "Two Hand Sword": "swords",
  "Two Hand Axe": "axes",
  "Two Hand Mace": "maces",
  FishingRod: "staves",
  Boots: "boots",
  Gloves: "gloves",
  "Body Armour": "body armour",
  Helmet: "helmets",
  Amulet: "amulets",
  Ring: "rings",
  Belt: "belts",
  Quiver: "quivers"
};

const rareNameSuffixes = {
  maces: [
    "Bane",
    "Blast",
    "Roar",
    "Batter",
    "Blow",
    "Blunt",
    "Brand",
    "Breaker",
    "Burst",
    "Crack",
    "Crusher",
    "Grinder",
    "Knell",
    "Mangler",
    "Ram",
    "Ruin",
    "Shatter",
    "Smasher",
    "Star",
    "Thresher",
    "Wreck"
  ],
  quivers: [
    "Arrow",
    "Barb",
    "Bite",
    "Bolt",
    "Brand",
    "Dart",
    "Flight",
    "Hail",
    "Impaler",
    "Nails",
    "Needle",
    "Quill",
    "Rod",
    "Shot",
    "Skewer",
    "Spear",
    "Spike",
    "Spire",
    "Stinger"
  ],
  amulets: [
    "Beads",
    "Braid",
    "Charm",
    "Choker",
    "Clasp",
    "Collar",
    "Idol",
    "Gorget",
    "Heart",
    "Locket",
    "Medallion",
    "Noose",
    "Pendant",
    "Rosary",
    "Scarab",
    "Talisman",
    "Torc"
  ],
  rings: [
    "Band",
    "Circle",
    "Coil",
    "Eye",
    "Finger",
    "Grasp",
    "Grip",
    "Gyre",
    "Hold",
    "Knot",
    "Knuckle",
    "Loop",
    "Nail",
    "Spiral",
    "Turn",
    "Twirl",
    "Whorl"
  ],
  belts: [
    "Bind",
    "Bond",
    "Buckle",
    "Clasp",
    "Cord",
    "Girdle",
    "Harness",
    "Lash",
    "Leash",
    "Lock",
    "Locket",
    "Shackle",
    "Snare",
    "Strap",
    "Tether",
    "Thread",
    "Trap",
    "Twine"
  ],
  boots: [
    "Dash",
    "Goad",
    "Hoof",
    "League",
    "March",
    "Pace",
    "Road",
    "Slippers",
    "Sole",
    "Span",
    "Spark",
    "Spur",
    "Stride",
    "Track",
    "Trail",
    "Tread",
    "Urge"
  ],
  gloves: [
    "Caress",
    "Claw",
    "Clutches",
    "Fingers",
    "Fist",
    "Grasp",
    "Grip",
    "Hand",
    "Hold",
    "Knuckle",
    "Mitts",
    "Nails",
    "Palm",
    "Paw",
    "Talons",
    "Touch",
    "Vise"
  ],
  "body armour": [
    "Carapace",
    "Cloak",
    "Coat",
    "Curtain",
    "Guardian",
    "Hide",
    "Jack",
    "Keep",
    "Mantle",
    "Pelt",
    "Salvation",
    "Sanctuary",
    "Shell",
    "Shelter",
    "Shroud",
    "Skin",
    "Suit",
    "Veil",
    "Ward",
    "Wrap"
  ],
  helmets: [
    "Brow",
    "Corona",
    "Cowl",
    "Crest",
    "Crown",
    "Dome",
    "Glance",
    "Guardian",
    "Halo",
    "Horn",
    "Keep",
    "Peak",
    "Salvation",
    "Shelter",
    "Star",
    "Veil",
    "Visage",
    "Visor",
    "Ward"
  ],
  "spirit shields": [
    "Ancient",
    "Anthem",
    "Call",
    "Chant",
    "Charm",
    "Emblem",
    "Guard",
    "Mark",
    "Pith",
    "Sanctuary",
    "Song",
    "Spell",
    "Star",
    "Ward",
    "Weaver",
    "Wish"
  ],
  shields: [
    "Aegis",
    "Badge",
    "Barrier",
    "Bastion",
    "Bulwark",
    "Duty",
    "Emblem",
    "Fend",
    "Guard",
    "Mark",
    "Refuge",
    "Rock",
    "Rook",
    "Sanctuary",
    "Span",
    "Tower",
    "Watch",
    "Wing"
  ],
  axes: [
    "Bane",
    "Beak",
    "Bite",
    "Butcher",
    "Edge",
    "Etcher",
    "Gnash",
    "Hunger",
    "Mangler",
    "Rend",
    "Roar",
    "Sever",
    "Slayer",
    "Song",
    "Spawn",
    "Splitter",
    "Crack",
    "Crusher",
    "Grinder",
    "Knell",
    "Mangler",
    "Ram",
    "Roar",
    "Ruin",
    "Shatter",
    "Smasher",
    "Star",
    "Thresher",
    "Wreck"
  ],
  sceptres: [
    "Bane",
    "Blow",
    "Breaker",
    "Call",
    "Chant",
    "Crack",
    "Crusher",
    "Cry",
    "Gnarl",
    "Grinder",
    "Knell",
    "Ram",
    "Roar",
    "Smasher",
    "Song",
    "Spell",
    "Star",
    "Weaver"
  ],
  staves: [
    "Bane",
    "Beam",
    "Branch",
    "Call",
    "Chant",
    "Cry",
    "Gnarl",
    "Goad",
    "Mast",
    "Pile",
    "Pillar",
    "Pole",
    "Post",
    "Roar",
    "Song",
    "Spell",
    "Spire",
    "Weaver"
  ],
  swords: [
    "Bane",
    "Barb",
    "Beak",
    "Bite",
    "Edge",
    "Fang",
    "Gutter",
    "Hunger",
    "Impaler",
    "Needle",
    "Razor",
    "Saw",
    "Scalpel",
    "Scratch",
    "Sever",
    "Skewer",
    "Slicer",
    "Song",
    "Spike",
    "Spiker",
    "Stinger",
    "Thirst"
  ],
  daggers: [
    "Bane",
    "Barb",
    "Bite",
    "Edge",
    "Etcher",
    "Fang",
    "Gutter",
    "Hunger",
    "Impaler",
    "Needle",
    "Razor",
    "Scalpel",
    "Scratch",
    "Sever",
    "Skewer",
    "Slicer",
    "Song",
    "Spike",
    "Stinger",
    "Thirst"
  ],
  claws: [
    "Bane",
    "Bite",
    "Edge",
    "Fang",
    "Fist",
    "Gutter",
    "Hunger",
    "Impaler",
    "Needle",
    "Razor",
    "Roar",
    "Scratch",
    "Skewer",
    "Slicer",
    "Song",
    "Spike",
    "Stinger",
    "Talons",
    "Thirst"
  ],
  bows: [
    "Bane",
    "Song",
    "Stinger",
    "Thirst",
    "Arch",
    "Barrage",
    "Blast",
    "Branch",
    "Breeze",
    "Fletch",
    "Guide",
    "Horn",
    "Mark",
    "Nock",
    "Rain",
    "Reach",
    "Siege",
    "Strike",
    "Thunder",
    "Twine",
    "Volley",
    "Wind",
    "Wing",
    "Bite"
  ],
  wands: [
    "Bane",
    "Song",
    "Thirst",
    "Branch",
    "Bite",
    "Edge",
    "Needle",
    "Scratch",
    "Barb",
    "Call",
    "Chant",
    "Charm",
    "Cry",
    "Gnarl",
    "Goad",
    "Spell",
    "Spire",
    "Weaver"
  ]
};

const rareNamePrefixes = [
  "Agony",
  "Apocalypse",
  "Armageddon",
  "Beast",
  "Behemoth",
  "Blight",
  "Blood",
  "Bramble",
  "Brimstone",
  "Brood",
  "Carrion",
  "Cataclysm",
  "Chimeric",
  "Corpse",
  "Corruption",
  "Damnation",
  "Death",
  "Demon",
  "Dire",
  "Dragon",
  "Dread",
  "Doom",
  "Dusk",
  "Eagle",
  "Empyrean",
  "Fate",
  "Foe",
  "Gale",
  "Ghoul",
  "Gloom",
  "Glyph",
  "Golem",
  "Grim",
  "Hate",
  "Havoc",
  "Honour",
  "Horror",
  "Hypnotic",
  "Kraken",
  "Loath",
  "Maelstrom",
  "Mind",
  "Miracle",
  "Morbid",
  "Oblivion",
  "Onslaught",
  "Pain",
  "Pandemonium",
  "Phoenix",
  "Plague",
  "Rage",
  "Rapture",
  "Rune",
  "Skull",
  "Sol",
  "Soul",
  "Sorrow",
  "Spirit",
  "Storm",
  "Tempest",
  "Torment",
  "Vengeance",
  "Victory",
  "Viper",
  "Vortex",
  "Woe",
  "Wrath"
];
